### ISSUE TITLE
Program sorts only using insert sort method

### ISSUE THREAD

**Issue by ToniaDemchuk** [itssmal/arraysort#1]
The latest version of program uses only insert sort method - it lacks the radio button selection of method:
```
function displayArr() {
    insertSort(array);
    sorted.textContent = "[" + array + "]";
}
```
https://github.com/itssmal/arraysort/blob/4d7a71bf8c0b6c30af037b4c7d76ae2f682845f2/script.js#L63

**Comment by itssmal** [comment]
> The latest version of program uses only insert sort method - it lacks the radio button selection of method:
> 
> ```
> function displayArr() {
>     insertSort(array);
>     sorted.textContent = "[" + array + "]";
> }
> ```
> 
> https://github.com/itssmal/arraysort/blob/4d7a71bf8c0b6c30af037b4c7d76ae2f682845f2/script.js#L63

But does it really matter which method to use(in that simple case) if the answer would be the same and we'd not see a difference in speed?
